apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cursor-share
  namespace: cursor-share
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  tls:
  - hosts:
    - "cursor-share.brennonloveless.com"
    secretName: cursor-share
  rules:
  - host: "cursor-share.brennonloveless.com"
    http:
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: cursor-share-api-service
              port:
                number: 8080
        - path: /
          pathType: Prefix
          backend:
            service:
              name: cursor-share-ui-service
              port:
                number: 80

